# Generated by Django 2.2.17 on 2021-01-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='icon',
            new_name='itemImage',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='hunter',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='votes_total',
        ),
        migrations.AddField(
            model_name='product',
            name='Id',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='Name',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
