# Generated by Django 2.2.17 on 2021-01-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donator', '0002_auto_20210117_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Phone',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
