# Generated by Django 2.2.17 on 2021-03-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donator', '0006_auto_20210321_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Id',
            new_name='govt_id',
        ),
    ]
