# Generated by Django 2.2.17 on 2021-01-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='insideImage',
            field=models.ImageField(upload_to='Ngoimages/'),
        ),
    ]
