# Generated by Django 2.2.17 on 2021-02-01 12:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ngo', '0004_products_owner1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Ngoprofile',
        ),
    ]
