# Generated by Django 2.2.17 on 2021-03-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0005_auto_20210201_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngoprofile',
            old_name='owner1',
            new_name='owner2',
        ),
    ]
