# Generated by Django 2.2.17 on 2021-03-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0006_auto_20210319_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngoprofile',
            name='Username',
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='certificates',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
