# Generated by Django 2.2.17 on 2021-01-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0003_auto_20210126_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Userimg',
            field=models.ImageField(default='SOME STRING', upload_to='User/'),
        ),
    ]
