# Generated by Django 2.2.17 on 2021-01-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0005_remove_profile_userimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
