# Generated by Django 2.2.17 on 2021-03-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0009_auto_20210321_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='owner2',
            new_name='profile_owner',
        ),
    ]
