# Generated by Django 2.2.17 on 2021-03-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20210129_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needrequest',
            name='body',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='needrequest',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
