# Generated by Django 2.2.17 on 2021-03-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20210319_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='needrequest',
            name='name',
            field=models.CharField(default='dummmy_name', max_length=200),
        ),
        migrations.AddField(
            model_name='needrequest',
            name='phone',
            field=models.CharField(default='0000000000', max_length=200),
        ),
    ]
